create table tb_account (id bigint not null auto_increment, cnpj varchar(255), company_name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_attachment (file_size bigint, id bigint not null auto_increment, trouble_ticket_id bigint, file_name varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table tb_comment (created_at datetime(6), created_by_id bigint, id bigint not null auto_increment, trouble_ticket_id bigint, text TEXT, primary key (id)) engine=InnoDB;
create table tb_contact (account_id bigint, id bigint not null auto_increment, user_id bigint, position varchar(255), primary key (id)) engine=InnoDB;
create table tb_ticket (assigned_to_user_id bigint, contact_id bigint, create_by_id bigint, created_time datetime(6), id bigint not null auto_increment, modified_time datetime(6), description varchar(255), title varchar(255), priority enum ('HIGH','LOW','MEDIUM','URGENT'), status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED'), primary key (id)) engine=InnoDB;
create table tb_trouble_ticket (created_by_id bigint, id bigint not null auto_increment, resolved_at datetime(6), resolved_by_id bigint, ticket_id bigint, root_cause varchar(255), solution TEXT, primary key (id)) engine=InnoDB;
create table tb_user (status bit, account_id bigint, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255), role enum ('ADMIN','CONTACT','CUSTOMER','TECHNICIAN'), primary key (id)) engine=InnoDB;
alter table tb_trouble_ticket add constraint UKlc9ufmqy6d2v1e51y5nv76t75 unique (ticket_id);
alter table tb_attachment add constraint FK5cptowhjs0kg0xdvrx258qsk5 foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_comment add constraint FKaa52wqq88hh6eiijscmq8t5q7 foreign key (created_by_id) references tb_user (id);
alter table tb_comment add constraint FKnd67fv3pgv1c2kc563ytbktwl foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_contact add constraint FKr4fnssocsmwudm4ctcelr6yuh foreign key (account_id) references tb_account (id);
alter table tb_contact add constraint FK2squhfn0wvup55w5jnxvxxgus foreign key (user_id) references tb_user (id);
alter table tb_ticket add constraint FKg5hs05phnpw9gxf1h1s5dh45p foreign key (assigned_to_user_id) references tb_user (id);
alter table tb_ticket add constraint FKplsubau3t1pr8oj5qbw7m0lx3 foreign key (contact_id) references tb_contact (id);
alter table tb_ticket add constraint FKrv7txokeapv268xcxvyh9hstv foreign key (create_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKl3fbrl66nf742b5ph5plikk3k foreign key (created_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FK6yg9wppifgookrtfdirl2sm7k foreign key (resolved_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKeuaphq47bi87tn8fmv0rwtoia foreign key (ticket_id) references tb_ticket (id);
alter table tb_user add constraint FKnflkc1qteu324uj0s1lsutf9v foreign key (account_id) references tb_account (id);
create table tb_account (id bigint not null auto_increment, cnpj varchar(255), company_name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_attachment (file_size bigint, id bigint not null auto_increment, trouble_ticket_id bigint, file_name varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table tb_comment (created_at datetime(6), created_by_id bigint, id bigint not null auto_increment, trouble_ticket_id bigint, text TEXT, primary key (id)) engine=InnoDB;
create table tb_contact (account_id bigint, id bigint not null auto_increment, user_id bigint, position varchar(255), primary key (id)) engine=InnoDB;
create table tb_ticket (assigned_to_user_id bigint, contact_id bigint, create_by_id bigint, created_time datetime(6), id bigint not null auto_increment, modified_time datetime(6), description varchar(255), title varchar(255), priority enum ('HIGH','LOW','MEDIUM','URGENT'), status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED'), primary key (id)) engine=InnoDB;
create table tb_trouble_ticket (created_by_id bigint, id bigint not null auto_increment, resolved_at datetime(6), resolved_by_id bigint, ticket_id bigint, root_cause varchar(255), solution TEXT, primary key (id)) engine=InnoDB;
create table tb_user (status bit, account_id bigint, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255), role enum ('ADMIN','CONTACT','CUSTOMER','TECHNICIAN'), primary key (id)) engine=InnoDB;
alter table tb_trouble_ticket add constraint UKlc9ufmqy6d2v1e51y5nv76t75 unique (ticket_id);
alter table tb_attachment add constraint FK5cptowhjs0kg0xdvrx258qsk5 foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_comment add constraint FKaa52wqq88hh6eiijscmq8t5q7 foreign key (created_by_id) references tb_user (id);
alter table tb_comment add constraint FKnd67fv3pgv1c2kc563ytbktwl foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_contact add constraint FKr4fnssocsmwudm4ctcelr6yuh foreign key (account_id) references tb_account (id);
alter table tb_contact add constraint FK2squhfn0wvup55w5jnxvxxgus foreign key (user_id) references tb_user (id);
alter table tb_ticket add constraint FKg5hs05phnpw9gxf1h1s5dh45p foreign key (assigned_to_user_id) references tb_user (id);
alter table tb_ticket add constraint FKplsubau3t1pr8oj5qbw7m0lx3 foreign key (contact_id) references tb_contact (id);
alter table tb_ticket add constraint FKrv7txokeapv268xcxvyh9hstv foreign key (create_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKl3fbrl66nf742b5ph5plikk3k foreign key (created_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FK6yg9wppifgookrtfdirl2sm7k foreign key (resolved_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKeuaphq47bi87tn8fmv0rwtoia foreign key (ticket_id) references tb_ticket (id);
alter table tb_user add constraint FKnflkc1qteu324uj0s1lsutf9v foreign key (account_id) references tb_account (id);
create table tb_account (id bigint not null auto_increment, cnpj varchar(255), company_name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_attachment (file_size bigint, id bigint not null auto_increment, trouble_ticket_id bigint, file_name varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table tb_comment (created_at datetime(6), created_by_id bigint, id bigint not null auto_increment, trouble_ticket_id bigint, text TEXT, primary key (id)) engine=InnoDB;
create table tb_contact (account_id bigint, id bigint not null auto_increment, user_id bigint, position varchar(255), primary key (id)) engine=InnoDB;
create table tb_ticket (assigned_to_user_id bigint, contact_id bigint, create_by_id bigint, created_time datetime(6), id bigint not null auto_increment, modified_time datetime(6), description varchar(255), title varchar(255), priority enum ('HIGH','LOW','MEDIUM','URGENT'), status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED'), primary key (id)) engine=InnoDB;
create table tb_trouble_ticket (created_by_id bigint, id bigint not null auto_increment, resolved_at datetime(6), resolved_by_id bigint, ticket_id bigint, root_cause varchar(255), solution TEXT, primary key (id)) engine=InnoDB;
create table tb_user (status bit, account_id bigint, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255), role enum ('ADMIN','CONTACT','CUSTOMER','TECHNICIAN'), primary key (id)) engine=InnoDB;
alter table tb_trouble_ticket add constraint UKlc9ufmqy6d2v1e51y5nv76t75 unique (ticket_id);
alter table tb_attachment add constraint FK5cptowhjs0kg0xdvrx258qsk5 foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_comment add constraint FKaa52wqq88hh6eiijscmq8t5q7 foreign key (created_by_id) references tb_user (id);
alter table tb_comment add constraint FKnd67fv3pgv1c2kc563ytbktwl foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_contact add constraint FKr4fnssocsmwudm4ctcelr6yuh foreign key (account_id) references tb_account (id);
alter table tb_contact add constraint FK2squhfn0wvup55w5jnxvxxgus foreign key (user_id) references tb_user (id);
alter table tb_ticket add constraint FKg5hs05phnpw9gxf1h1s5dh45p foreign key (assigned_to_user_id) references tb_user (id);
alter table tb_ticket add constraint FKplsubau3t1pr8oj5qbw7m0lx3 foreign key (contact_id) references tb_contact (id);
alter table tb_ticket add constraint FKrv7txokeapv268xcxvyh9hstv foreign key (create_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKl3fbrl66nf742b5ph5plikk3k foreign key (created_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FK6yg9wppifgookrtfdirl2sm7k foreign key (resolved_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKeuaphq47bi87tn8fmv0rwtoia foreign key (ticket_id) references tb_ticket (id);
alter table tb_user add constraint FKnflkc1qteu324uj0s1lsutf9v foreign key (account_id) references tb_account (id);
create table tb_account (id bigint not null auto_increment, cnpj varchar(255), company_name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_attachment (file_size bigint, id bigint not null auto_increment, trouble_ticket_id bigint, file_name varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table tb_comment (created_at datetime(6), created_by_id bigint, id bigint not null auto_increment, trouble_ticket_id bigint, text TEXT, primary key (id)) engine=InnoDB;
create table tb_contact (account_id bigint, id bigint not null auto_increment, user_id bigint, position varchar(255), primary key (id)) engine=InnoDB;
create table tb_ticket (assigned_to_user_id bigint, contact_id bigint, create_by_id bigint, created_time datetime(6), id bigint not null auto_increment, modified_time datetime(6), description varchar(255), title varchar(255), priority enum ('HIGH','LOW','MEDIUM','URGENT'), status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED'), primary key (id)) engine=InnoDB;
create table tb_trouble_ticket (created_by_id bigint, id bigint not null auto_increment, resolved_at datetime(6), resolved_by_id bigint, ticket_id bigint, root_cause varchar(255), solution TEXT, primary key (id)) engine=InnoDB;
create table tb_user (status bit, account_id bigint, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255), role enum ('ADMIN','CONTACT','CUSTOMER','TECHNICIAN'), primary key (id)) engine=InnoDB;
alter table tb_trouble_ticket add constraint UKlc9ufmqy6d2v1e51y5nv76t75 unique (ticket_id);
alter table tb_attachment add constraint FK5cptowhjs0kg0xdvrx258qsk5 foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_comment add constraint FKaa52wqq88hh6eiijscmq8t5q7 foreign key (created_by_id) references tb_user (id);
alter table tb_comment add constraint FKnd67fv3pgv1c2kc563ytbktwl foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_contact add constraint FKr4fnssocsmwudm4ctcelr6yuh foreign key (account_id) references tb_account (id);
alter table tb_contact add constraint FK2squhfn0wvup55w5jnxvxxgus foreign key (user_id) references tb_user (id);
alter table tb_ticket add constraint FKg5hs05phnpw9gxf1h1s5dh45p foreign key (assigned_to_user_id) references tb_user (id);
alter table tb_ticket add constraint FKplsubau3t1pr8oj5qbw7m0lx3 foreign key (contact_id) references tb_contact (id);
alter table tb_ticket add constraint FKrv7txokeapv268xcxvyh9hstv foreign key (create_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKl3fbrl66nf742b5ph5plikk3k foreign key (created_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FK6yg9wppifgookrtfdirl2sm7k foreign key (resolved_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKeuaphq47bi87tn8fmv0rwtoia foreign key (ticket_id) references tb_ticket (id);
alter table tb_user add constraint FKnflkc1qteu324uj0s1lsutf9v foreign key (account_id) references tb_account (id);
create table tb_account (id bigint not null auto_increment, cnpj varchar(255), company_name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_attachment (file_size bigint, id bigint not null auto_increment, trouble_ticket_id bigint, file_name varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table tb_comment (created_at datetime(6), created_by_id bigint, id bigint not null auto_increment, trouble_ticket_id bigint, text TEXT, primary key (id)) engine=InnoDB;
create table tb_contact (account_id bigint, id bigint not null auto_increment, user_id bigint, position varchar(255), primary key (id)) engine=InnoDB;
create table tb_ticket (assigned_to_user_id bigint, contact_id bigint, create_by_id bigint, created_time datetime(6), id bigint not null auto_increment, modified_time datetime(6), description varchar(255), title varchar(255), priority enum ('HIGH','LOW','MEDIUM','URGENT'), status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED'), primary key (id)) engine=InnoDB;
create table tb_trouble_ticket (created_by_id bigint, id bigint not null auto_increment, resolved_at datetime(6), resolved_by_id bigint, ticket_id bigint, root_cause varchar(255), solution TEXT, primary key (id)) engine=InnoDB;
create table tb_user (status bit, account_id bigint, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255), role enum ('ADMIN','CONTACT','CUSTOMER','TECHNICIAN'), primary key (id)) engine=InnoDB;
alter table tb_trouble_ticket add constraint UKlc9ufmqy6d2v1e51y5nv76t75 unique (ticket_id);
alter table tb_attachment add constraint FK5cptowhjs0kg0xdvrx258qsk5 foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_comment add constraint FKaa52wqq88hh6eiijscmq8t5q7 foreign key (created_by_id) references tb_user (id);
alter table tb_comment add constraint FKnd67fv3pgv1c2kc563ytbktwl foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_contact add constraint FKr4fnssocsmwudm4ctcelr6yuh foreign key (account_id) references tb_account (id);
alter table tb_contact add constraint FK2squhfn0wvup55w5jnxvxxgus foreign key (user_id) references tb_user (id);
alter table tb_ticket add constraint FKg5hs05phnpw9gxf1h1s5dh45p foreign key (assigned_to_user_id) references tb_user (id);
alter table tb_ticket add constraint FKplsubau3t1pr8oj5qbw7m0lx3 foreign key (contact_id) references tb_contact (id);
alter table tb_ticket add constraint FKrv7txokeapv268xcxvyh9hstv foreign key (create_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKl3fbrl66nf742b5ph5plikk3k foreign key (created_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FK6yg9wppifgookrtfdirl2sm7k foreign key (resolved_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKeuaphq47bi87tn8fmv0rwtoia foreign key (ticket_id) references tb_ticket (id);
alter table tb_user add constraint FKnflkc1qteu324uj0s1lsutf9v foreign key (account_id) references tb_account (id);
create table tb_account (id bigint not null auto_increment, cnpj varchar(255), company_name varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table tb_attachment (file_size bigint, id bigint not null auto_increment, trouble_ticket_id bigint, file_name varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table tb_comment (created_at datetime(6), created_by_id bigint, id bigint not null auto_increment, trouble_ticket_id bigint, text TEXT, primary key (id)) engine=InnoDB;
create table tb_contact (account_id bigint, id bigint not null auto_increment, user_id bigint, position varchar(255), primary key (id)) engine=InnoDB;
create table tb_ticket (assigned_to_user_id bigint, contact_id bigint, create_by_id bigint, created_time datetime(6), id bigint not null auto_increment, modified_time datetime(6), description varchar(255), title varchar(255), priority enum ('HIGH','LOW','MEDIUM','URGENT'), status enum ('CLOSED','IN_PROGRESS','OPEN','RESOLVED'), primary key (id)) engine=InnoDB;
create table tb_trouble_ticket (created_by_id bigint, id bigint not null auto_increment, resolved_at datetime(6), resolved_by_id bigint, ticket_id bigint, root_cause varchar(255), solution TEXT, primary key (id)) engine=InnoDB;
create table tb_user (status bit, account_id bigint, id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255), role enum ('ADMIN','CONTACT','CUSTOMER','TECHNICIAN'), primary key (id)) engine=InnoDB;
alter table tb_trouble_ticket add constraint UKlc9ufmqy6d2v1e51y5nv76t75 unique (ticket_id);
alter table tb_attachment add constraint FK5cptowhjs0kg0xdvrx258qsk5 foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_comment add constraint FKaa52wqq88hh6eiijscmq8t5q7 foreign key (created_by_id) references tb_user (id);
alter table tb_comment add constraint FKnd67fv3pgv1c2kc563ytbktwl foreign key (trouble_ticket_id) references tb_trouble_ticket (id);
alter table tb_contact add constraint FKr4fnssocsmwudm4ctcelr6yuh foreign key (account_id) references tb_account (id);
alter table tb_contact add constraint FK2squhfn0wvup55w5jnxvxxgus foreign key (user_id) references tb_user (id);
alter table tb_ticket add constraint FKg5hs05phnpw9gxf1h1s5dh45p foreign key (assigned_to_user_id) references tb_user (id);
alter table tb_ticket add constraint FKplsubau3t1pr8oj5qbw7m0lx3 foreign key (contact_id) references tb_contact (id);
alter table tb_ticket add constraint FKrv7txokeapv268xcxvyh9hstv foreign key (create_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKl3fbrl66nf742b5ph5plikk3k foreign key (created_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FK6yg9wppifgookrtfdirl2sm7k foreign key (resolved_by_id) references tb_user (id);
alter table tb_trouble_ticket add constraint FKeuaphq47bi87tn8fmv0rwtoia foreign key (ticket_id) references tb_ticket (id);
alter table tb_user add constraint FKnflkc1qteu324uj0s1lsutf9v foreign key (account_id) references tb_account (id);
